config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'help' => "static_pages#help"
  
  get 'static_pages/about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:banana) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class = "navbar navbar-fixed-top">
		<div class = "container">
			<nav>
				<ul class = "nav navbar">
					<li><%= link_to "Homebase", root_path %></li>
					<li><%= link_to "Help me out", help_path %></li>
				</ul>
			</nav>
		</div>
	</header>

<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>About us</h1>

app/views/static_pages/help.html.erb
<% provide(:banana, "Help") %>
<h1>Help</h1>
<p><div> ipsum dolor sit amet, consectetur adipisicing elit. Quis accusamus vero quos temporibus eos totam voluptas. Praesentium a, explicabo enim, assumenda, eveniet ab rem necessitatibus minima sit, numquam molestias deleniti!</div></p>

app/views/static_pages/home.html.erb
<% provide(:banana, "Home") %>

<h1>Breadit</h1>
<p>
	<a href="http://breadpeople.tumblr.com/">Bread people</a>
</p>